export const INITIALIZE = 'INITIALIZE';

export const SET_ACTIVE_QUESTION = 'SET_ACTIVE_QUESTION';
export const UPDATE_ACTIVE_QUESTION = 'UPDATE_ACTIVE_QUESTION';
export const ADD_QUESTION = 'ADD_QUESTION';
export const DELETE_QUESTION = 'DELETE_QUESTION';

export const SAVE_QUESTIONS_REQUEST = 'SAVE_QUESTIONS_REQUEST';
export const SAVE_QUESTIONS_SUCCESS = 'SAVE_QUESTIONS_SUCCESS';
export const SAVE_QUESTIONS_FAILURE = 'SAVE_QUESTIONS_FAILURE';

export const DELETE_QUESTION_REQUEST = 'DELETE_QUESTION_REQUEST';
export const DELETE_QUESTION_SUCCESS = 'DELETE_QUESTION_SUCCESS';
export const DELETE_QUESTION_FAILURE = 'DELETE_QUESTION_FAILURE';
