export const GAME_PLAY_REQUEST = 'GAME_PLAY_REQUEST';
export const GAME_PLAY_SUCCESS = 'GAME_PLAY_SUCCESS';
export const GAME_PLAY_FAILURE = 'GAME_PLAY_FAILURE';

export const UPDATE_PLAYERS_LIST = 'UPDATE_PLAYERS_LIST';
export const QUESTION_INTRO = 'QUESTION_INTRO';
export const QUESTION_START = 'QUESTION_START';
export const QUESTION_END = 'QUESTION_END';

export const GAME_OVER = 'GAME_OVER';
